name: GitHub CI
on: [push]

concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  macos_build:
    name: macOS Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i -e 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      run: |
        bash scripts/build.macos.release.sh
        bash scripts/build.macos.clients.sh
        mv base stairspeedtest
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: stairspeedtest_reborn_darwin64
        path: stairspeedtest/
    - name: Package Release
      if: startsWith(github.ref, 'refs/tags/')
      run: tar czf stairspeedtest_reborn_darwin64.tar.gz stairspeedtest
    - name: Draft Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: stairspeedtest_reborn_darwin64.tar.gz
        draft: true

